import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/sideBar";
import NavBar from "@/components/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Mainlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-full">
      <SideBar />
      <div className="px-20 w-full">
        <NavBar />
        {children}
      </div>
    </div>
  );
}
